project -new
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_avalon_st_adapter_channel_adapter_0.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_irq_mapper.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1_avalon_st_adapter_005_error_adapter_0.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1_avalon_st_adapter_error_adapter_0.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_avalon_st_handshake_clock_crosser.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_avalon_st_clock_crosser.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_avalon_st_pipeline_base.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_std_synchronizer_nocut.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_merlin_width_adapter.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_merlin_address_alignment.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1_rsp_mux_001.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_merlin_arbitrator.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1_rsp_mux.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1_rsp_demux_003.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1_rsp_demux.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1_cmd_mux_003.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1_cmd_mux.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1_cmd_demux_001.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1_cmd_demux.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_merlin_burst_adapter.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_merlin_burst_adapter_uncmpr.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_merlin_burst_adapter_13_1.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_merlin_burst_adapter_new.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_incr_burst_converter.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_wrap_burst_converter.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_default_burst_converter.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_avalon_st_pipeline_stage.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_merlin_traffic_limiter.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_merlin_reorder_memory.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_avalon_sc_fifo.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1_router_007.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1_router_005.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1_router_002.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1_router_001.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1_router.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_merlin_slave_agent.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_merlin_master_agent.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_merlin_slave_translator.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_merlin_master_translator.sv}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/soc1.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_reset_controller.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_reset_synchronizer.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_avalon_st_adapter.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1_avalon_st_adapter_005.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_1_avalon_st_adapter.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_mm_interconnect_0.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_up_avalon_video_vga_timing.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_video_vga_controller_0.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_up_video_scaler_shrink.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_up_video_scaler_multiply_width.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/altera_up_video_scaler_multiply_height.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_video_scaler_0.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_video_rgb_resampler_0.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_video_pixel_buffer_dma_0.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_video_dual_clock_buffer_0.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_timer_0.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_sdram.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_ram.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_pll.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_jtag_uart.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_cpu.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_cpu_cpu.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_cpu_cpu_debug_slave_sysclk.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_cpu_cpu_debug_slave_tck.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_cpu_cpu_debug_slave_wrapper.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_cpu_cpu_mult_cell.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/soc1/synthesis/submodules/soc1_cpu_cpu_test_bench.v}
add_file -verilog {C:/Users/Afshin/Desktop/vga/p1/DE10_LITE_Golden_Top.v}
add_file -constraint {vga1.sdc}
set_option -top_module DE10_LITE_Golden_Top
set_option -technology 
set_option -part 
set_option -package 
set_option -write_verilog 0
set_option -write_vhdl 0
set_option -write_vif 0
set_option -write_apr_constraint 0
project -result_file ./DE10_LITE_Golden_Top.vqm
project -log_file ./DE10_LITE_Golden_Top.srr
set_option -frequency auto
project -run
project -save vga1.prj
